apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/schmidtp0740/medbo-backend:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/schmidtp0740/medbo-backend:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: medbo-backend
        chartPath: charts/medbo-backend
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/schmidtp0740/medbo-backend"
          image.tag: "{{.DIGEST_HEX}}"
